### ISSUE TITLE
Brigade-exporter not collecting metrics.

### ISSUE THREAD

**Issue by prshntsingh2010** [slok/brigade-exporter#6]
I deployed Brigade-exporter using helm, now neither it gives error nor the metrics. it gets reflected in my Prometheus though, but collects no metrics.I have installed brigade-exporter in the same namespace as that of Brigade  @slok  can you help?
![Screenshot (61)_LI](https://user-images.githubusercontent.com/49158697/58613504-8d30b280-82d3-11e9-9323-86b35bb90239.jpg)

**Comment by slok** [comment]
Hi @prshntsingh2010! can you post the logs of the exporter? do you have RBAC activated on the cluster?

**Comment by prshntsingh2010** [comment]
Hey @slok , yes, I have RBAC activated

![Screenshot (65)_LI](https://user-images.githubusercontent.com/49158697/58614173-493ead00-82d5-11e9-87e6-315ab60ebbdb.jpg)

Here are the logs of the exporter. 
![Screenshot (63)](https://user-images.githubusercontent.com/49158697/58613949-aab24c00-82d4-11e9-8913-2d9ca1f16488.png)

Restarting the pod gives this log:
```
{"level":"info","msg":"listening on :9480","src":"group.go:38","time":"2019-05-30T06:58:13Z"}
```

**Comment by slok** [comment]
Thanks for the info.

Did you specify the namespace flag on the exporter, where the exporter should check the brigade?

example:

```yaml
...
 containers:                                                                                             
  - args:                               
    - --namespace={BRIGADE_NS}
    image: quay.io/slok/brigade-exporter:v0.2.1
...
```
